-- 0004b_seed_products_brands.sql — src/data/brands.ts·src/data/products.ts 시드
-- 0004_products_brands.sql 실행 후, Supabase SQL Editor에서 1회 실행.
-- 컬럼은 컬럼으로, 나머지 필드는 detail jsonb로 옮긴다. 화면 렌더는 detail 병합 후 기존과 동일해야 한다.

insert into public.brands (id, name, is_visible, detail) values
  ('b1', '페네핏 (PENEFIT)', true, '{"logo":"/brands/penefit.svg","description":"반려동물의 식탁을 더 즐겁고 건강하게 만드는 영양 토핑 브랜드","philosophy":"페네핏은 반려동물의 식사 시간을 단순히 배를 채우는 순간이 아니라,\n건강한 즐거움과 기록이 함께 쌓이는 시간으로 바라봅니다.\n\n한 끼의 즐거움이 내일의 건강으로 이어지는 것.\n페네핏은 그 작고 꾸준한 다정함을 제품으로 제안합니다.","auditGrade":"A+","auditPoints":["식사 보조 제품으로 활용하기 쉬운 구성","강아지와 고양이 모두를 고려한 제품 라인","다양한 맛 옵션으로 기호성 선택 가능","소분 또는 샘플 형태 구매 흐름에 적합","보호자가 급여 반응을 확인하기 쉬운 제품 구조"],"auditReport":{"reportNo":"BOA-2026-004","auditedAt":"2026.06","status":"Audit Completed","headline":"반려동물의 식탁을 넓히는 영양 설계","summaryTitle":"성분을 감추지 않는 자신감","summary":"좋은 간식은 아이들이 즐겁게 먹을 수 있어야 하지만, 맛만으로 충분하지 않습니다. 페네핏은 기호성 뒤의 영양 설계와 원료 공개, 특정 아이들이 먹지 못하는 상황까지 함께 고민합니다.","selectionReason":"반려동물 간식은 많지만 더 많은 아이들이 함께 먹을 수 있는 방법까지 고민하는 브랜드는 많지 않습니다. 페네핏은 단순히 기호성만 앞세우지 않고, 알레르기 반응으로 기존 제품을 먹기 어려운 아이들까지 고려해 별도의 레시피를 개발하고 있었습니다. 원료와 맞춤 영양 설계, 반려동물 식품영양사 참여 여부, 국내 생산 체계와 실제 운영 태도를 함께 검토한 결과 제품 운영 전반에 반려동물 중심의 기준이 반영돼 있음을 확인했습니다.","process":["브랜드 철학 및 제품 개발 방향성","반려동물 식품영양사 참여 여부","원료 선정 및 영양 설계 방식","국내 생산 체계 및 품질 관리 기준","알레르기 대응 제품 개발 과정","실제 운영 태도 및 브랜드 문화","제품 확장 계획 및 지속 가능성"]},"representativeProductIds":["p1","p2","p3"],"relatedConcernSlugs":["picky","nutrition"],"isRecommended":true}'::jsonb),
  ('b2', '오미프로 (OMIPRO)', true, '{"logo":"/brands/omipro.svg","description":"반려동물의 건강한 일상을 위한 케어 중심 영양 브랜드","philosophy":"오미프로는 반려동물의 일상 관리와 건강한 생활 루틴을 돕는 브랜드입니다.\n\n매일의 작은 관리가 건강한 습관이 되도록 돕는 것.\n오미프로는 반려동물의 일상 속 케어 루틴을 제안합니다.","auditGrade":"A","auditPoints":["일상 관리 목적에 적합한 제품 구성","보호자가 꾸준히 사용하기 쉬운 구조","과장된 치료 표현보다 관리 중심 메시지 사용","강아지와 고양이 라인 구분 가능","반려동물 생활 루틴과 연결 가능"],"representativeProductIds":["p4","p5","p6"],"relatedConcernSlugs":["nutrition","skin","senior"],"isRecommended":true}'::jsonb),
  ('b3', '노블독 (NobleDog)', true, '{"logo":"/brands/nobledog.svg","description":"반려동물의 구강 건강을 위한 집요한 케어 브랜드","philosophy":"노블독은 반려동물의 구강 건강을 중심으로 제품을 설계하는 브랜드입니다.\n\n팔기 위한 제품이 아닌, 살리기 위한 집요함.\n노블독은 느리지만 단단한 길을 선택한 브랜드입니다.","auditGrade":"A+","auditPoints":["구강 건강 중심의 명확한 제품 방향","동물용의약외품 신고 및 품질 관리 기준 확인","시험성적서 기반 신뢰 자료 보유","보호자가 사용하기 쉬운 스프레이형 제품 구조","직접 분사 또는 물/사료에 섞어 사용할 수 있는 편의성"],"representativeProductIds":["p7","p8"],"relatedConcernSlugs":["oral"],"isRecommended":true}'::jsonb),
  ('b4', '캣코드 (Catcode)', true, '{"logo":"/brands/catcode.svg","description":"고양이와 보호자의 교감을 위한 브러싱 케어 브랜드","philosophy":"캣코드는 고양이의 편안함과 보호자의 다정한 손길을 함께 고려한 케어 브랜드입니다.\n\n당신이 받은 고결한 사랑에 답하는 가장 다정한 언어.\n캣코드는 관리가 아닌 교감의 시간을 제안합니다.","auditGrade":"A","auditPoints":["고양이가 거부감 없이 받아들이기 쉬운 케어 방향","보호자와 고양이의 관계성을 고려한 제품 구조","손가락 사이에 자연스럽게 안정되는 손잡이 설계","브러싱과 마사지가 함께 가능한 사용 경험","공간과 감성을 해치지 않는 오브제형 디자인"],"representativeProductIds":["p9","p10","p11"],"relatedConcernSlugs":["grooming","stress"],"isRecommended":false,"isNew":true}'::jsonb),
  ('b5', '알로밍 (ALLOMING)', true, '{"logo":"/brands/alloming.svg","description":"반려가족의 공간과 감성을 고려한 라이프스타일 케어 브랜드","philosophy":"알로밍은 반려동물과 함께 사는 공간의 분위기, 사용감, 감성을 함께 고려하는 브랜드입니다.\n\n반려동물 제품이 단순한 용품을 넘어\n우리 집의 분위기와 자연스럽게 어울리는 선택이 되도록 제안합니다.","auditGrade":"B+","auditPoints":["생활 공간과 어울리는 디자인 방향","반려동물과 보호자가 함께 쓰기 좋은 구성","주거와 미학 카테고리 연결 가능","브러싱과 교감 경험을 함께 고려","고급 편집샵형 브랜드관에 적합"],"representativeProductIds":["p12","p13","p14"],"relatedConcernSlugs":["grooming","stress","living"],"isRecommended":false,"isNew":true}'::jsonb);

insert into public.products (id, brand_id, name, price, sale_price, category, category_slug, lifestyle_category, pet_type, stock, rating, review_count, is_visible, is_best, is_recommended, detail) values
  ('p1', 'b1', '페네핏 팔레트 파우더 본품팩', null, null, '식사와 영양', 'dining-and-nourish', '식사와 영양', 'both', 100, 4.8, 342, true, true, true, '{"brandName":"페네핏","concernTags":["picky","nutrition"],"ageGroup":"all","image":"/products/p1.svg","summary":"밥 안 먹는 강아지 고양이 필수품, 영양간식 밥꾸템","description":"아이의 기호성과 영양 균형을 함께 고려한 파우더 형태의 제품을 통해, 매일의 식사가 더 부드럽고 지속 가능한 관리로 이어질 수 있도록 돕습니다.","isMembersOnlyPrice":true,"options":[{"id":"opt1_1","name":"레드(4g*15ea)","price":0,"stock":50},{"id":"opt1_2","name":"그린(4g*15ea)","price":0,"stock":50},{"id":"opt1_3","name":"옐로우(4g*15ea)","price":0,"stock":50},{"id":"opt1_4","name":"베이지(4g*15ea)","price":0,"stock":50},{"id":"opt1_5","name":"딥그린(4g*15ea)","price":0,"stock":50},{"id":"opt1_6","name":"퍼플(4g*15ea)","price":0,"stock":50}]}'::jsonb),
  ('p2', 'b1', '페네핏 팔레트 파우더 버라이어티팩', null, null, '식사와 영양', 'dining-and-nourish', '식사와 영양', 'both', 200, 4.9, 512, true, true, true, '{"brandName":"페네핏","concernTags":["picky","nutrition"],"ageGroup":"all","image":"/products/p2.svg","summary":"다양한 맛을 한 번에 경험할 수 있는 영양 파우더 샘플 구성","description":"아이의 기호성과 영양 균형을 함께 고려한 파우더 형태의 제품을 통해, 매일의 식사가 더 부드럽고 지속 가능한 관리로 이어질 수 있도록 돕습니다.","isMembersOnlyPrice":true,"options":[{"id":"opt2_1","name":"버라이어티팩(4g*6ea)","price":0,"stock":100}]}'::jsonb),
  ('p3', 'b1', '페네핏 팔레트 파우더 3구팩', null, null, '식사와 영양', 'dining-and-nourish', '식사와 영양', 'both', 50, 4.7, 128, true, false, true, '{"brandName":"페네핏","concernTags":["picky","nutrition"],"ageGroup":"all","image":"/products/p3.svg","summary":"우리 아이의 기호를 가볍게 확인할 수 있는 3구 구성","description":"아이의 기호성과 영양 균형을 함께 고려한 파우더 형태의 제품을 통해, 매일의 식사가 더 부드럽고 지속 가능한 관리로 이어질 수 있도록 돕습니다.","isMembersOnlyPrice":true,"options":[{"id":"opt3_1","name":"옐로우(4g*3ea)","price":0,"stock":30},{"id":"opt3_2","name":"그린(4g*3ea)","price":0,"stock":20},{"id":"opt3_3","name":"딥그린(4g*3ea)","price":0,"stock":30},{"id":"opt3_4","name":"퍼플(4g*3ea)","price":0,"stock":20},{"id":"opt3_5","name":"레드(4g*3ea)","price":0,"stock":30},{"id":"opt3_6","name":"베이지(4g*3ea)","price":0,"stock":20}]}'::jsonb),
  ('p4', 'b2', '오미프로 강아지 건강 영양제', null, null, '건강과 케어', 'wellness-and-care', '건강과 케어', 'dog', 30, 4.9, 245, true, true, true, '{"brandName":"오미프로","concernTags":["nutrition","skin","senior"],"ageGroup":"all","image":"/products/p4.svg","summary":"강아지의 건강한 일상 루틴을 위한 데일리 케어 영양제","description":"반려동물의 일상 관리와 건강한 생활 루틴을 돕는 오미프로의 데일리 영양제입니다.","options":[{"id":"opt4_1","name":"강아지용","price":0,"stock":30}]}'::jsonb),
  ('p5', 'b2', '오미프로 고양이 건강 영양제', null, null, '건강과 케어', 'wellness-and-care', '건강과 케어', 'cat', 150, 4.6, 89, true, false, true, '{"brandName":"오미프로","concernTags":["nutrition","skin","senior"],"ageGroup":"all","image":"/products/p5.svg","summary":"고양이의 식사와 생활 습관을 방해하지 않는 데일리 영양 케어","description":"반려동물의 일상 관리와 건강한 생활 루틴을 돕는 오미프로의 데일리 영양제입니다.","options":[{"id":"opt5_1","name":"고양이용","price":0,"stock":150}]}'::jsonb),
  ('p6', 'b2', '오미프로 반려동물 건강 영양제 4 in 1', null, null, '식사와 영양', 'dining-and-nourish', '식사와 영양', 'both', 200, 4.8, 420, true, true, true, '{"brandName":"오미프로","concernTags":["nutrition","skin","senior"],"ageGroup":"all","image":"/products/p6.svg","summary":"강아지와 고양이의 기본 건강 관리를 위한 복합 케어 영양제","description":"반려동물의 일상 관리와 건강한 생활 루틴을 돕는 오미프로의 복합 케어 영양제입니다.","options":[{"id":"opt6_1","name":"1개","price":0,"stock":100},{"id":"opt6_2","name":"2개 세트","price":0,"stock":100}]}'::jsonb),
  ('p7', 'b3', '노블독 구강 케어 스프레이', null, null, '구강과 위생', 'fragrance-and-hygiene', '구강과 위생', 'both', 80, 4.5, 75, true, true, true, '{"brandName":"노블독","concernTags":["oral"],"ageGroup":"all","image":"/products/p7.svg","summary":"반려동물의 입안과 숨결을 부드럽게 관리하는 구강 케어 스프레이","description":"아이의 숨결과 구강 건강을 오래 지키는 구강 관리 스프레이입니다.","options":[{"id":"opt7_1","name":"기본형","price":0,"stock":80}]}'::jsonb),
  ('p8', 'b3', '노블독 반려동물 구강 관리 미스트', null, null, '구강과 위생', 'fragrance-and-hygiene', '구강과 위생', 'both', 300, 4.9, 630, true, false, true, '{"brandName":"노블독","concernTags":["oral"],"ageGroup":"all","image":"/products/p8.svg","summary":"직접 분사하거나 물과 사료에 섞어 사용할 수 있는 구강 관리 미스트","description":"아이의 숨결과 구강 건강을 오래 지키는 구강 관리 미스트입니다.","options":[{"id":"opt8_1","name":"기본형","price":0,"stock":300}]}'::jsonb),
  ('p9', 'b4', '캣코드 고양이 브러쉬', null, null, '그루밍과 브러싱', 'grooming-and-brushing', '그루밍과 브러싱', 'cat', 120, 4.4, 42, true, true, true, '{"brandName":"캣코드","concernTags":["grooming","stress"],"ageGroup":"all","image":"/products/p9.svg","summary":"고양이와 보호자의 교감을 위한 부드러운 브러싱 케어 제품","description":"브러싱을 관리가 아닌 교감의 시간으로 바꿉니다.","options":[{"id":"opt9_1","name":"베이지","price":0,"stock":40},{"id":"opt9_2","name":"핑크","price":0,"stock":40},{"id":"opt9_3","name":"민트","price":0,"stock":40}]}'::jsonb),
  ('p10', 'b4', '캣코드 브러싱 케어 오브제', null, null, '생활과 오브제', 'living-and-objet', '생활과 오브제', 'cat', 150, 4.7, 315, true, false, false, '{"brandName":"캣코드","concernTags":["grooming","stress"],"ageGroup":"all","image":"/products/p10.svg","summary":"관리 도구를 넘어 공간과 어울리는 고양이 케어 오브제","description":"브러싱을 관리가 아닌 교감의 시간으로 바꿉니다.","options":[{"id":"opt10_1","name":"기본형","price":0,"stock":150}]}'::jsonb),
  ('p11', 'b4', '캣코드 고양이 마사지 브러쉬', null, null, '그루밍과 브러싱', 'grooming-and-brushing', '그루밍과 브러싱', 'cat', 400, 4.9, 890, true, true, true, '{"brandName":"캣코드","concernTags":["grooming","stress"],"ageGroup":"all","image":"/products/p11.svg","summary":"털 관리와 부드러운 마사지 경험을 함께 제공하는 고양이 브러쉬","description":"브러싱을 관리가 아닌 교감의 시간으로 바꿉니다.","options":[{"id":"opt11_1","name":"베이지","price":0,"stock":100},{"id":"opt11_2","name":"핑크","price":0,"stock":100},{"id":"opt11_3","name":"민트","price":0,"stock":100},{"id":"opt11_4","name":"블랙","price":0,"stock":100}]}'::jsonb),
  ('p12', 'b5', '알로밍 브러쉬 케어 세트', null, null, '그루밍과 브러싱', 'grooming-and-brushing', '그루밍과 브러싱', 'both', 80, 4.8, 210, true, true, true, '{"brandName":"알로밍","concernTags":["grooming","stress","living"],"ageGroup":"all","image":"/products/p12.svg","summary":"반려동물과 보호자의 교감 시간을 위한 감성 브러쉬 케어 세트","description":"기능과 감성을 함께 고려한 케어 오브제를 제안합니다.","options":[{"id":"opt12_1","name":"기본 세트","price":0,"stock":80}]}'::jsonb),
  ('p13', 'b5', '알로밍 고양이 브러쉬', null, null, '그루밍과 브러싱', 'grooming-and-brushing', '그루밍과 브러싱', 'cat', 120, 4.7, 36, true, false, false, '{"brandName":"알로밍","concernTags":["grooming","stress","living"],"ageGroup":"all","image":"/products/p13.svg","summary":"고양이의 편안함과 공간의 감성을 함께 고려한 브러쉬","description":"기능과 감성을 함께 고려한 케어 오브제를 제안합니다.","options":[{"id":"opt13_1","name":"베이지","price":0,"stock":40},{"id":"opt13_2","name":"핑크","price":0,"stock":40},{"id":"opt13_3","name":"민트","price":0,"stock":40}]}'::jsonb),
  ('p14', 'b5', '알로밍 교감 브러쉬', null, null, '생활과 오브제', 'living-and-objet', '생활과 오브제', 'both', 100, 4.8, 50, true, true, true, '{"brandName":"알로밍","concernTags":["grooming","stress","living"],"ageGroup":"all","image":"/products/p14.svg","summary":"받은 사랑에 답하는 다정한 손길을 제품으로 만든 교감형 브러쉬","description":"기능과 감성을 함께 고려한 케어 오브제를 제안합니다.","options":[{"id":"opt14_1","name":"기본형","price":0,"stock":100}]}'::jsonb);
