-- 0018_reseed_brands_products.sql — 정본(src/data/brands.ts b1~b9 · products.ts p1~p22) 전체 재시드
-- 배경: DB는 0004b(브랜드 5·상품 14·구명칭) 이후 상품이 미동기. 정본은 2026-07-10 갱신(쿠팡 sourceUrl 포함).
-- 관리자 수정분 없음 확인(DB 현재값 == 0004b 원본) → 전체 upsert 안전. gen-0018.mjs로 기계 생성(수기 전사 금지).

insert into public.brands (id, name, is_visible, detail) values
  ('b1', '페네핏 (PENEFIT)', true, '{"officialUrl":"https://penefit.co.kr/","sourceUrls":["https://penefit.co.kr/product/%ED%8C%94%EB%A0%88%ED%8A%B8%ED%8C%8C%EC%9A%B0%EB%8D%94-20-%EB%A3%A8%ED%8B%B4-%EC%BC%80%EC%96%B4-5%EC%A2%85/90/","https://penefit.co.kr/product/%ED%8E%98%EB%84%A4%ED%95%8F-%EB%8F%99%EA%B2%B0%EA%B1%B4%EC%A1%B0-%ED%8A%B8%EB%A6%BF-%EC%A0%B8%ED%82%A4-%EA%B0%84%EC%8B%9D-7%EC%A2%85/78/"],"logo":"/brands/penefit-official.png","description":"반려동물의 식탁을 더 즐겁고 건강하게 만드는 영양 토핑 브랜드","philosophy":"페네핏은 반려동물의 식사 시간을 단순히 배를 채우는 순간이 아니라,\n건강한 즐거움과 기록이 함께 쌓이는 시간으로 바라봅니다.\n\n한 끼의 즐거움이 내일의 건강으로 이어지는 것.\n페네핏은 그 작고 꾸준한 다정함을 제품으로 제안합니다.","auditPoints":["식사 보조 제품으로 활용하기 쉬운 구성","강아지와 고양이 모두를 고려한 제품 라인","다양한 맛 옵션으로 기호성 선택 가능","소분 또는 샘플 형태 구매 흐름에 적합","보호자가 급여 반응을 확인하기 쉬운 제품 구조"],"auditReport":{"reportNo":"BOA-2026-004","auditedAt":"2026.06","status":"Audit Completed","headline":"반려동물의 식탁을 넓히는 영양 설계","summaryTitle":"성분을 감추지 않는 자신감","summary":"좋은 간식은 아이들이 즐겁게 먹을 수 있어야 하지만, 맛만으로 충분하지 않습니다. 페네핏은 기호성 뒤의 영양 설계와 원료 공개, 특정 아이들이 먹지 못하는 상황까지 함께 고민합니다.","selectionReason":"반려동물 간식은 많지만 더 많은 아이들이 함께 먹을 수 있는 방법까지 고민하는 브랜드는 많지 않습니다. 페네핏은 단순히 기호성만 앞세우지 않고, 알레르기 반응으로 기존 제품을 먹기 어려운 아이들까지 고려해 별도의 레시피를 개발하고 있었습니다. 원료와 맞춤 영양 설계, 반려동물 식품영양사 참여 여부, 국내 생산 체계와 실제 운영 태도를 함께 검토한 결과 제품 운영 전반에 반려동물 중심의 기준이 반영돼 있음을 확인했습니다.","process":["브랜드 철학 및 제품 개발 방향성","반려동물 식품영양사 참여 여부","원료 선정 및 영양 설계 방식","국내 생산 체계 및 품질 관리 기준","알레르기 대응 제품 개발 과정","실제 운영 태도 및 브랜드 문화","제품 확장 계획 및 지속 가능성"]},"representativeProductIds":["p1","p2","p3"],"relatedConcernSlugs":["picky","nutrition"],"isRecommended":true}'::jsonb),
  ('b2', '오미프로 (OMIPRO)', true, '{"officialUrl":"http://www.omipro.co.kr/","sourceUrls":["https://exhi.daara.co.kr/akppe/m/view.php?idx=308611&language_chk=en","https://exhi.daara.co.kr/akppe/view.php?idx=308612","https://buykorea.org/ec/prd/selectSvcDetail.do?goodsSn=3703785"],"logo":"/brands/omipro-official.png","description":"반려동물의 체취와 분변 냄새 관리를 위한 기능성 사료형 간식 브랜드","philosophy":"오미프로는 반려동물의 식사 루틴 안에서 냄새 고민을 관리하는 방법을 제안합니다.\n\n제품의 기능과 급여 방법을 명확히 안내하고, 치료를 대신하지 않는 생활 관리의 언어를 지향합니다.","auditPoints":["강아지용 OMIPRO-D와 고양이용 OMIPRO-C 라인 구분","사료에 섞거나 간식처럼 급여할 수 있는 형태","체취·분변 냄새 저감 목적의 명확한 제품 방향","기능성 표현은 자료 확인 후 백조오브제 기준으로 검수","수의학적 치료 효능으로 오인되지 않도록 관리 중심 안내"],"representativeProductIds":["p4","p5","p6"],"relatedConcernSlugs":["digestion","skin"],"isRecommended":true}'::jsonb),
  ('b3', '노블독 (NobleDog)', true, '{"sourceUrls":["https://www.coupang.com/vp/products/8769224002","https://www.coupang.com/vp/products/9305418924"],"logo":"/brands/nobledog-clean.png","description":"반려동물의 구강 건강을 위한 집요한 케어 브랜드","philosophy":"노블독은 반려동물의 구강 건강을 중심으로 제품을 설계하는 브랜드입니다.\n\n팔기 위한 제품이 아닌, 살리기 위한 집요함.\n노블독은 느리지만 단단한 길을 선택한 브랜드입니다.","auditPoints":["구강 건강 중심의 명확한 제품 방향","공식 제조·성분·시험 자료 수령 후 입점 검수","구취·프라그 관련 표현은 확인된 근거 범위에서만 사용","보호자가 사용하기 쉬운 스프레이형 제품 구조","직접 분사 또는 물/사료에 섞어 사용할 수 있는 편의성"],"representativeProductIds":["p7","p8"],"relatedConcernSlugs":["oral"],"isRecommended":true}'::jsonb),
  ('b4', '캣코드 (Catcode)', false, '{"logo":"/brands/catcode.svg","description":"고양이와 보호자의 교감을 위한 브러싱 케어 브랜드","philosophy":"캣코드는 고양이의 편안함과 보호자의 다정한 손길을 함께 고려한 케어 브랜드입니다.\n\n당신이 받은 고결한 사랑에 답하는 가장 다정한 언어.\n캣코드는 관리가 아닌 교감의 시간을 제안합니다.","auditPoints":["고양이가 거부감 없이 받아들이기 쉬운 케어 방향","보호자와 고양이의 관계성을 고려한 제품 구조","손가락 사이에 자연스럽게 안정되는 손잡이 설계","브러싱과 마사지가 함께 가능한 사용 경험","공간과 감성을 해치지 않는 오브제형 디자인"],"representativeProductIds":["p9","p10","p11"],"relatedConcernSlugs":["grooming","stress"],"isRecommended":false,"isNew":true}'::jsonb),
  ('b5', '알로밍 (ALLOMING)', true, '{"officialUrl":"https://alloming.com/","sourceUrls":["https://alloming.com/shop_view/?idx=13","https://alloming.com/shop_view/?idx=6","https://alloming.com/certifications"],"logo":"/brands/alloming-official.png","description":"반려동물과 보호자의 교감을 위한 트루그루밍 브러시 브랜드","philosophy":"알로밍은 브러싱을 단순한 털 관리가 아니라 반려동물과 보호자가 서로를 돌보는 시간으로 바라봅니다.\n\n손에 잡히는 사용감과 모듈 구조를 함께 설계해 매일의 그루밍 루틴을 제안합니다.","auditPoints":["강아지·고양이 공용 그루밍 브러시","단모·장모용 모듈 구분","브러싱과 보호자 교감 경험을 함께 고려","국내 브랜드·제조 정보 확인 가능","색상과 모듈을 선택할 수 있는 상품 구조"],"representativeProductIds":["p12","p13","p14"],"relatedConcernSlugs":["grooming","stress","living"],"isRecommended":false,"isNew":true}'::jsonb),
  ('b6', 're펫 (RePet)', true, '{"sourceUrls":["https://www.coupang.com/vp/products/7940009634","https://www.coupang.com/vp/products/4581101510","https://www.coupang.com/vp/products/7856404250","https://www.coupang.com/vp/products/9334824830","https://www.coupang.com/vp/products/8309521234"],"logo":"/brands/repet-display.svg","description":"장 건강·위생·생활 케어 상품 후보를 확인 중인 브랜드","philosophy":"re펫은 현재 공개 판매 페이지에서 상품 후보를 수집한 단계입니다.\n\n공식 제조사와 브랜드 운영 주체를 확인한 뒤 백조오브제의 판매 상품으로 최종 승인합니다.","auditPoints":["공식 운영 주체와 제조사 확인 필요","장 건강·샴푸·배변 유도제·분유 상품군 후보","상품별 성분·사용법·품질 자료 확인 필요","검증 완료 전 과장된 기능성 문구 사용 금지","출처 URL은 관리자 검수용으로만 보관"],"representativeProductIds":["p19","p20"],"relatedConcernSlugs":["digestion","skin"],"isRecommended":false,"isNew":true}'::jsonb),
  ('b7', '메종슈슈 (Maison Chouchou)', true, '{"officialUrl":"https://maisonchouchou-pet.com/","sourceUrls":["https://maisonchouchou-pet.com/product/for-ur-dog-bamboo-cardigan/163/","https://maisonchouchou-pet.com/product/gold-ops/191","https://maisonchouchou-pet.com/product/atelier-angel-dresspink/199/","https://maisonchouchou-pet.com/product/%EB%A9%94%EC%A2%85%EC%8A%88%EC%8A%88-%EB%A6%AC%EB%B3%B8-%EC%A7%84%EC%A3%BC-%EB%AA%A9%EA%B1%B8%EC%9D%B4/205"],"logo":"/brands/maison-chouchou-official.png","description":"반려견을 위한 의류와 액세서리를 제안하는 패션 브랜드","philosophy":"메종슈슈는 반려견의 일상과 특별한 순간을 위한 의류와 액세서리를 만듭니다.\n\n사이즈와 제작·배송 조건을 함께 안내하는 섬세한 패션 경험을 제안합니다.","auditPoints":["반려견 의류·드레스·목걸이 상품군","상품별 사이즈 선택이 중요한 카테고리","핸드메이드·소량 제작 상품의 배송 기간 확인","주문 제작 상품 교환·반품 조건 별도 안내","백조오브제 내부 배송 정책과 조율 필요"],"representativeProductIds":["p15","p16"],"relatedConcernSlugs":["stress","living"],"isRecommended":true,"isNew":true}'::jsonb),
  ('b8', '챠콜스토리 (Charcoal Story)', true, '{"officialUrl":"https://charcoalstory.com/","sourceUrls":["https://www.coupang.com/vp/products/9468681405","https://www.coupang.com/vp/products/9479160233","https://www.coupang.com/vp/products/9468730890","https://www.coupang.com/vp/products/9466864793"],"logo":"/brands/charcoal-story-official.png","description":"참숯 소재를 활용한 반려동물 탈취·생활 케어 브랜드","philosophy":"챠콜스토리는 참숯 소재의 특성을 반려동물의 생활 공간에 맞게 제안합니다.\n\n고양이 화장실과 방석 주변을 더 쾌적하게 관리하는 생활 케어를 지향합니다.","auditPoints":["고양이 모래 탈취제와 참숯 탈취 매트 상품군","반려동물 사용 공간에 맞는 제품만 선별","어항·화분용 상품은 반려동물관에서 제외","소재·사용 기간·교체 방법 확인 필요","탈취 표현은 제품 자료 범위 내에서 안내"],"representativeProductIds":["p17","p18"],"relatedConcernSlugs":["digestion","living"],"isRecommended":true,"isNew":true}'::jsonb),
  ('b9', '써니 사이드업 (Sunny Side Up)', true, '{"officialUrl":"https://www.ssup.co.kr/","sourceUrls":["https://www.ssup.co.kr/goods/view?no=38","https://ssup.co.kr/goods/view?no=43","https://www.ssup.co.kr/service/company"],"logo":"/brands/sunny-side-up-official.png","description":"애니마크·퍼르르펙트·파티애니멀을 운영하는 펫 라이프스타일 브랜드","philosophy":"써니 사이드업은 반려동물과 사람이 함께 더 즐겁게 살아가는 제품을 만듭니다.\n\n운영 브랜드와 개별 제품 브랜드를 분리해, 사용 대상과 기능을 정확하게 안내합니다.","auditPoints":["애니마크 반려동물 피부 연고 상품 확인","퍼르르펙트·파티애니멀 등 제품 브랜드 구분","반려동물용과 사람용 상품을 분리 노출","피부 케어 상품의 사용 대상·주의사항 확인","향수·장난감·케어 제품으로 확장 가능한 구조"],"representativeProductIds":["p21","p22"],"relatedConcernSlugs":["skin","stress"],"isRecommended":true,"isNew":true}'::jsonb)
on conflict (id) do update set
  name = excluded.name,
  is_visible = excluded.is_visible,
  detail = excluded.detail;

insert into public.products (id, brand_id, name, price, sale_price, category, category_slug, lifestyle_category, pet_type, stock, rating, review_count, is_visible, is_best, is_recommended, detail) values
  ('p1', 'b1', '페네핏 팔레트파우더 2.0 루틴 케어 5종', null, null, '식사와 영양', 'dining-and-nourish', '식사와 영양', 'both', 100, 4.8, 342, true, true, true, '{"brandName":"페네핏","sourceUrl":"https://penefit.co.kr/product/%ED%8C%94%EB%A0%88%ED%8A%B8%ED%8C%8C%EC%9A%B0%EB%8D%94-20-%EB%A3%A8%ED%8B%B4-%EC%BC%80%EC%96%B4-5%EC%A2%85/90/","sourceVerifiedAt":"2026-07-10","catalogStatus":"draft","concernTags":["picky","nutrition"],"ageGroup":"all","image":"/products/p1.svg","summary":"밥 안 먹는 강아지 고양이 필수품, 영양간식 밥꾸템","description":"아이의 기호성과 영양 균형을 함께 고려한 파우더 형태의 제품을 통해, 매일의 식사가 더 부드럽고 지속 가능한 관리로 이어질 수 있도록 돕습니다.","isMembersOnlyPrice":true,"options":[{"id":"opt1_1","name":"레드(4g*15ea)","price":0,"stock":50},{"id":"opt1_2","name":"그린(4g*15ea)","price":0,"stock":50},{"id":"opt1_3","name":"옐로우(4g*15ea)","price":0,"stock":50},{"id":"opt1_4","name":"베이지(4g*15ea)","price":0,"stock":50},{"id":"opt1_5","name":"딥그린(4g*15ea)","price":0,"stock":50},{"id":"opt1_6","name":"퍼플(4g*15ea)","price":0,"stock":50}]}'::jsonb),
  ('p2', 'b1', '페네핏 팔레트파우더 2.0 올인원 케어 박스', null, null, '식사와 영양', 'dining-and-nourish', '식사와 영양', 'both', 200, 4.9, 512, true, true, true, '{"brandName":"페네핏","sourceUrl":"https://penefit.co.kr/product/%ED%8C%94%EB%A0%88%ED%8A%B8%ED%8C%8C%EC%9A%B0%EB%8D%94-20-%EC%98%AC%EC%9D%B8%EC%9B%90-%EC%BC%80%EC%96%B4-%EB%B0%95%EC%8A%A4-%EC%9E%90%EC%82%AC%EB%AA%B0-%EC%A0%84%EC%9A%A9-%EC%A6%9D%EC%A0%95/88/","sourceVerifiedAt":"2026-07-10","catalogStatus":"draft","concernTags":["picky","nutrition"],"ageGroup":"all","image":"/products/p2.svg","summary":"다양한 맛을 한 번에 경험할 수 있는 영양 파우더 샘플 구성","description":"아이의 기호성과 영양 균형을 함께 고려한 파우더 형태의 제품을 통해, 매일의 식사가 더 부드럽고 지속 가능한 관리로 이어질 수 있도록 돕습니다.","isMembersOnlyPrice":true,"options":[{"id":"opt2_1","name":"버라이어티팩(4g*6ea)","price":0,"stock":100}]}'::jsonb),
  ('p3', 'b1', '페네핏 팔레트파우더 2.0 30일 스타터 키트', null, null, '식사와 영양', 'dining-and-nourish', '식사와 영양', 'both', 50, 4.7, 128, true, false, true, '{"brandName":"페네핏","sourceUrl":"https://penefit.co.kr/product/%ED%8C%94%EB%A0%88%ED%8A%B8%ED%8C%8C%EC%9A%B0%EB%8D%94-20-30%EC%9D%BC-%EC%8A%A4%ED%83%80%ED%84%B0-%ED%82%A4%ED%8A%B8-%EB%B2%84%EB%9D%BC%EC%9D%B4%EC%96%B4%ED%8B%B0-%ED%8C%A9-%ED%8F%AC%ED%95%A8/80/","sourceVerifiedAt":"2026-07-10","catalogStatus":"draft","concernTags":["picky","nutrition"],"ageGroup":"all","image":"/products/p3.svg","summary":"우리 아이의 기호를 가볍게 확인할 수 있는 3구 구성","description":"아이의 기호성과 영양 균형을 함께 고려한 파우더 형태의 제품을 통해, 매일의 식사가 더 부드럽고 지속 가능한 관리로 이어질 수 있도록 돕습니다.","isMembersOnlyPrice":true,"options":[{"id":"opt3_1","name":"옐로우(4g*3ea)","price":0,"stock":30},{"id":"opt3_2","name":"그린(4g*3ea)","price":0,"stock":20},{"id":"opt3_3","name":"딥그린(4g*3ea)","price":0,"stock":30},{"id":"opt3_4","name":"퍼플(4g*3ea)","price":0,"stock":20},{"id":"opt3_5","name":"레드(4g*3ea)","price":0,"stock":30},{"id":"opt3_6","name":"베이지(4g*3ea)","price":0,"stock":20}]}'::jsonb),
  ('p4', 'b2', '오미프로 OMIPRO-D 강아지용 냄새 케어 간식', null, null, '건강과 케어', 'wellness-and-care', '건강과 케어', 'dog', 30, 4.9, 245, true, true, true, '{"brandName":"오미프로","sourceUrl":"https://exhi.daara.co.kr/akppe/view.php?idx=308612","sourceVerifiedAt":"2026-07-10","catalogStatus":"draft","concernTags":["digestion","skin"],"ageGroup":"all","image":"/products/p4.svg","summary":"강아지 사료에 섞거나 간식처럼 급여하는 냄새 케어 제품","description":"오미프로가 공개한 강아지용 사료형 간식 후보입니다. 백조오브제에서는 성분표와 기능성 표시 자료를 확인한 뒤 체취·분변 냄새 관리 범위에서 안내합니다.","options":[{"id":"opt4_1","name":"강아지용","price":0,"stock":30}]}'::jsonb),
  ('p5', 'b2', '오미프로 OMIPRO-C 고양이용 냄새 케어 간식', null, null, '건강과 케어', 'wellness-and-care', '건강과 케어', 'cat', 150, 4.6, 89, true, false, true, '{"brandName":"오미프로","sourceUrl":"https://exhi.daara.co.kr/akppe/m/view.php?idx=308611&language_chk=en","sourceVerifiedAt":"2026-07-10","catalogStatus":"draft","concernTags":["digestion","skin"],"ageGroup":"all","image":"/products/p5.svg","summary":"고양이 사료에 섞거나 간식처럼 급여하는 냄새 케어 제품","description":"오미프로가 공개한 고양이용 사료형 간식 후보입니다. 백조오브제에서는 고양이 급여법과 성분 자료를 확인한 뒤 생활 관리 상품으로 안내합니다.","options":[{"id":"opt5_1","name":"고양이용","price":0,"stock":150}]}'::jsonb),
  ('p6', 'b2', '오미프로 반려동물 냄새 케어 세트', null, null, '식사와 영양', 'dining-and-nourish', '식사와 영양', 'both', 200, 4.8, 420, true, true, true, '{"brandName":"오미프로","sourceUrl":"https://www.busanpetshow.co.kr/product/product_view.htm?idx=30126","sourceVerifiedAt":"2026-07-10","catalogStatus":"draft","concernTags":["digestion","skin"],"ageGroup":"all","image":"/products/p6.svg","summary":"강아지용·고양이용 라인을 함께 비교하는 냄새 케어 구성","description":"오미프로의 공개 제품군을 백조오브제에서 강아지용과 고양이용으로 나누어 판매하기 위한 내부 구성입니다.","options":[{"id":"opt6_1","name":"강아지용 OMIPRO-D","price":0,"stock":100},{"id":"opt6_2","name":"고양이용 OMIPRO-C","price":0,"stock":100}]}'::jsonb),
  ('p7', 'b3', '노블독 냥치하개 뿌리는 치약 100ml', null, null, '구강과 위생', 'fragrance-and-hygiene', '구강과 위생', 'both', 80, 4.5, 75, true, true, true, '{"brandName":"노블독","sourceUrl":"https://www.coupang.com/vp/products/8769224002","sourceVerifiedAt":"2026-07-10","catalogStatus":"draft","concernTags":["oral"],"ageGroup":"all","image":"/products/p7.svg","summary":"강아지와 고양이에게 사용하는 무색무취 타입 구강 케어 스프레이","description":"노블독 공개 판매 페이지에서 확인한 뿌리는 치약 상품입니다. 백조오브제에서는 제조·성분·시험 자료 확인 후 구취와 플라그 관리 범위로 안내합니다.","options":[{"id":"opt7_1","name":"기본형","price":0,"stock":80}]}'::jsonb),
  ('p8', 'b3', '노블독 구강 청결 스프레이 100ml', null, null, '구강과 위생', 'fragrance-and-hygiene', '구강과 위생', 'both', 300, 4.9, 630, true, false, true, '{"brandName":"노블독","sourceUrl":"https://www.coupang.com/vp/products/9305418924","sourceVerifiedAt":"2026-07-10","catalogStatus":"draft","concernTags":["oral"],"ageGroup":"all","image":"/products/p8.svg","summary":"반려동물의 일상 구강 관리를 위한 스프레이형 상품 후보","description":"노블독 공개 판매 페이지에서 확인한 구강 청결 스프레이 상품 후보입니다. 사용 대상과 급여·분사 방법은 입점 자료를 받은 뒤 확정합니다.","options":[{"id":"opt8_1","name":"기본형","price":0,"stock":300}]}'::jsonb),
  ('p9', 'b4', '캣코드 고양이 브러쉬', null, null, '그루밍과 브러싱', 'grooming-and-brushing', '그루밍과 브러싱', 'cat', 120, 4.4, 42, true, true, true, '{"brandName":"캣코드","concernTags":["grooming","stress"],"ageGroup":"all","image":"/products/p9.svg","summary":"고양이와 보호자의 교감을 위한 부드러운 브러싱 케어 제품","description":"브러싱을 관리가 아닌 교감의 시간으로 바꿉니다.","options":[{"id":"opt9_1","name":"베이지","price":0,"stock":40},{"id":"opt9_2","name":"핑크","price":0,"stock":40},{"id":"opt9_3","name":"민트","price":0,"stock":40}]}'::jsonb),
  ('p10', 'b4', '캣코드 브러싱 케어 오브제', null, null, '생활과 오브제', 'living-and-objet', '생활과 오브제', 'cat', 150, 4.7, 315, true, false, false, '{"brandName":"캣코드","concernTags":["grooming","stress"],"ageGroup":"all","image":"/products/p10.svg","summary":"관리 도구를 넘어 공간과 어울리는 고양이 케어 오브제","description":"브러싱을 관리가 아닌 교감의 시간으로 바꿉니다.","options":[{"id":"opt10_1","name":"기본형","price":0,"stock":150}]}'::jsonb),
  ('p11', 'b4', '캣코드 고양이 마사지 브러쉬', null, null, '그루밍과 브러싱', 'grooming-and-brushing', '그루밍과 브러싱', 'cat', 400, 4.9, 890, true, true, true, '{"brandName":"캣코드","concernTags":["grooming","stress"],"ageGroup":"all","image":"/products/p11.svg","summary":"털 관리와 부드러운 마사지 경험을 함께 제공하는 고양이 브러쉬","description":"브러싱을 관리가 아닌 교감의 시간으로 바꿉니다.","options":[{"id":"opt11_1","name":"베이지","price":0,"stock":100},{"id":"opt11_2","name":"핑크","price":0,"stock":100},{"id":"opt11_3","name":"민트","price":0,"stock":100},{"id":"opt11_4","name":"블랙","price":0,"stock":100}]}'::jsonb),
  ('p12', 'b5', '알로밍 트루그루밍 브러시 단모용 그립 모듈', null, null, '그루밍과 브러싱', 'grooming-and-brushing', '그루밍과 브러싱', 'both', 80, 4.8, 210, true, true, true, '{"brandName":"알로밍","sourceUrl":"https://alloming.com/shop_view/?idx=13","sourceVerifiedAt":"2026-07-10","catalogStatus":"draft","concernTags":["grooming","stress","living"],"ageGroup":"all","image":"/products/p12.svg","summary":"강아지와 고양이의 단모 그루밍을 위한 교감형 브러시","description":"알로밍 공식 상품 페이지에서 확인한 단모용 트루그루밍 브러시입니다. 백조오브제에서는 색상·모듈 옵션을 내부 상품 옵션으로 구성합니다.","options":[{"id":"opt12_1","name":"기본 세트","price":0,"stock":80}]}'::jsonb),
  ('p13', 'b5', '알로밍 트루그루밍 브러시', null, null, '그루밍과 브러싱', 'grooming-and-brushing', '그루밍과 브러싱', 'cat', 120, 4.7, 36, true, false, false, '{"brandName":"알로밍","sourceUrl":"https://alloming.com/shop_view/?idx=6","sourceVerifiedAt":"2026-07-10","catalogStatus":"draft","concernTags":["grooming","stress","living"],"ageGroup":"all","image":"/products/p13.svg","summary":"반려동물과 보호자의 교감을 중심으로 설계한 그루밍 브러시","description":"알로밍의 트루그루밍 브러시 대표 상품입니다. 브러싱을 관리가 아닌 교감의 시간으로 제안하는 상품군으로 분류합니다.","options":[{"id":"opt13_1","name":"베이지","price":0,"stock":40},{"id":"opt13_2","name":"핑크","price":0,"stock":40},{"id":"opt13_3","name":"민트","price":0,"stock":40}]}'::jsonb),
  ('p14', 'b5', '알로밍 트루그루밍 브러시 다크그레이', null, null, '생활과 오브제', 'living-and-objet', '생활과 오브제', 'both', 100, 4.8, 50, true, true, true, '{"brandName":"알로밍","sourceUrl":"https://alloming.com/store/?idx=12","sourceVerifiedAt":"2026-07-10","catalogStatus":"draft","concernTags":["grooming","stress","living"],"ageGroup":"all","image":"/products/p14.svg","summary":"공간에 자연스럽게 어울리는 다크그레이 컬러 브러시","description":"알로밍 트루그루밍 브러시의 다크그레이 컬러 상품입니다. 색상은 백조오브제 내부 옵션으로 관리합니다.","options":[{"id":"opt14_1","name":"기본형","price":0,"stock":100}]}'::jsonb),
  ('p15', 'b7', '[for ur dog] Bamboo Cardigan', 98000, 68600, '패션과 액세서리', 'fashion-and-accessories', '패션과 액세서리', 'dog', 0, 0, 0, true, false, true, '{"brandName":"메종슈슈","sourceUrl":"https://maisonchouchou-pet.com/product/for-ur-dog-bamboo-cardigan/163/","sourceVerifiedAt":"2026-07-10","catalogStatus":"draft","concernTags":["stress","living"],"ageGroup":"all","image":"/products/p15.svg","summary":"반려견을 위한 대나무 소재 카디건","description":"메종슈슈 공식몰에서 확인한 반려견용 Bamboo Cardigan입니다. 백조오브제에서는 사이즈와 주문 제작·배송 조건을 확인한 뒤 판매합니다.","shippingNotice":"브랜드 주문 제작 여부와 사이즈별 재고 확인 후 배송일을 안내합니다.","options":[{"id":"opt15_xs","name":"XS","price":0,"stock":0},{"id":"opt15_s","name":"S","price":0,"stock":0},{"id":"opt15_m","name":"M","price":0,"stock":0},{"id":"opt15_l","name":"L","price":0,"stock":0},{"id":"opt15_xl","name":"XL","price":0,"stock":0},{"id":"opt15_xxl","name":"XXL","price":0,"stock":0}]}'::jsonb),
  ('p16', 'b7', '메종슈슈 Gold Ops', null, null, '패션과 액세서리', 'fashion-and-accessories', '패션과 액세서리', 'dog', 0, 0, 0, true, false, true, '{"brandName":"메종슈슈","sourceUrl":"https://maisonchouchou-pet.com/product/gold-ops/191","sourceVerifiedAt":"2026-07-10","catalogStatus":"draft","concernTags":["stress","living"],"ageGroup":"all","image":"/products/p16.svg","summary":"반려견의 특별한 순간을 위한 골드 컬러 오프숄더 드레스","description":"메종슈슈 공식몰에서 확인한 Gold Ops 상품입니다. 사이즈·재고·내부 판매가는 입점 확정 후 백조오브제 기준으로 입력합니다.","shippingNotice":"주문 제작 상품은 제작 기간이 추가될 수 있습니다.","options":[{"id":"opt16_default","name":"사이즈 선택 후 주문","price":0,"stock":0}],"isMembersOnlyPrice":true}'::jsonb),
  ('p17', 'b8', '차콜프레시 그레인 고양이 모래 탈취제 500g', null, null, '구강과 위생', 'fragrance-and-hygiene', '구강과 위생', 'cat', 0, 0, 0, true, false, true, '{"brandName":"챠콜스토리","sourceUrl":"https://www.coupang.com/vp/products/9468681405","sourceVerifiedAt":"2026-07-10","catalogStatus":"draft","concernTags":["digestion","living"],"ageGroup":"all","image":"/products/p17.svg","summary":"고양이 화장실 주변 냄새 관리를 위한 참숯 탈취제","description":"차콜스토리 공개 판매 페이지에서 확인한 고양이 모래용 탈취제입니다. 사용량·원료·교체 주기는 상품 자료를 확인해 백조오브제 상세정보에 반영합니다.","options":[{"id":"opt17_default","name":"500g","price":0,"stock":0}],"isMembersOnlyPrice":true}'::jsonb),
  ('p18', 'b8', '차콜프레시 참숯 탈취 매트', null, null, '생활과 오브제', 'living-and-objet', '생활과 오브제', 'both', 0, 0, 0, true, false, true, '{"brandName":"챠콜스토리","sourceUrl":"https://www.coupang.com/vp/products/9468730890","sourceVerifiedAt":"2026-07-10","catalogStatus":"draft","concernTags":["living"],"ageGroup":"all","image":"/products/p18.svg","summary":"강아지·고양이 방석과 쿠션 내부에 사용하는 참숯 탈취 매트","description":"차콜스토리 공개 판매 페이지에서 확인한 반려동물 방석·쿠션용 참숯 탈취 매트입니다. 규격과 사용 기간은 입점 자료 확인 후 확정합니다.","options":[{"id":"opt18_default","name":"기본형","price":0,"stock":0}],"isMembersOnlyPrice":true}'::jsonb),
  ('p19', 'b6', 'RePet 강아지 뿌리는 배변유도제 80ml × 2개', null, null, '구강과 위생', 'fragrance-and-hygiene', '구강과 위생', 'dog', 0, 0, 0, true, false, false, '{"brandName":"re펫","sourceUrl":"https://www.coupang.com/vp/products/9334824830","sourceVerifiedAt":"2026-07-10","catalogStatus":"draft","concernTags":["digestion"],"ageGroup":"all","image":"/products/p19.svg","summary":"강아지 배변 훈련을 위한 스프레이형 배변 유도제 후보","description":"공개 판매 페이지에서 RePet 명칭으로 확인한 강아지용 배변 유도제입니다. 백조오브제에서는 사용 방법과 안전 주의사항을 확인한 뒤 판매합니다.","options":[{"id":"opt19_default","name":"80ml × 2개","price":0,"stock":0}],"isMembersOnlyPrice":true}'::jsonb),
  ('p20', 'b6', 'RePet 강아지·고양이 약용·진정 샴푸 400ml', null, null, '구강과 위생', 'fragrance-and-hygiene', '구강과 위생', 'both', 0, 0, 0, true, false, false, '{"brandName":"re펫","sourceUrl":"https://www.coupang.com/vp/products/4581101510","sourceVerifiedAt":"2026-07-10","catalogStatus":"draft","concernTags":["skin"],"ageGroup":"all","image":"/products/p20.svg","summary":"강아지와 고양이의 목욕·피부 관리 상품 후보","description":"공개 판매 페이지에서 RePet 명칭으로 노출된 샴푸 상품 후보입니다. 약용·진정 등 표현은 공식 자료 확인 후 백조오브제 상품명과 상세페이지에서 조정합니다.","options":[{"id":"opt20_default","name":"400ml","price":0,"stock":0}],"isMembersOnlyPrice":true}'::jsonb),
  ('p21', 'b9', '애니마크 반려동물 피부 연고', 8000, 5900, '건강과 케어', 'wellness-and-care', '건강과 케어', 'both', 0, 0, 0, true, false, true, '{"brandName":"써니 사이드업","sourceUrl":"https://www.ssup.co.kr/goods/view?no=38","sourceVerifiedAt":"2026-07-10","catalogStatus":"draft","concernTags":["skin"],"ageGroup":"all","image":"/products/p21.svg","summary":"발바닥·턱 주변 등 반려동물 피부 보습 케어 상품","description":"써니 사이드업 공식몰의 애니마크 피부 연고 상품입니다. 백조오브제에서는 적용 부위와 사용 주의사항을 공식 자료 기준으로 안내합니다.","options":[{"id":"opt21_default","name":"기본형","price":0,"stock":0}],"isMembersOnlyPrice":true}'::jsonb),
  ('p22', 'b9', '퍼르르펙트 고양이 캣닢 향수', null, null, '생활과 오브제', 'fragrance-and-hygiene', '생활과 오브제', 'cat', 0, 0, 0, true, false, false, '{"brandName":"써니 사이드업","sourceUrl":"https://www.ssup.co.kr/","sourceVerifiedAt":"2026-07-10","catalogStatus":"draft","concernTags":["stress"],"ageGroup":"all","image":"/products/p22.svg","summary":"써니 사이드업 공식몰에서 확인한 고양이용 향수·캣닢 상품 후보","description":"써니 사이드업 공식몰의 고양이 제품군에서 확인한 퍼르르펙트 상품 후보입니다. 사용 대상과 분사 방법을 확인한 뒤 백조오브제 내부 상품으로 확정합니다.","options":[{"id":"opt22_default","name":"기본형","price":0,"stock":0}],"isMembersOnlyPrice":true}'::jsonb)
on conflict (id) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  price = excluded.price,
  sale_price = excluded.sale_price,
  category = excluded.category,
  category_slug = excluded.category_slug,
  lifestyle_category = excluded.lifestyle_category,
  pet_type = excluded.pet_type,
  stock = excluded.stock,
  rating = excluded.rating,
  review_count = excluded.review_count,
  is_visible = excluded.is_visible,
  is_best = excluded.is_best,
  is_recommended = excluded.is_recommended,
  detail = excluded.detail;
